### ISSUE TITLE
After installation still wrong language settings

### ISSUE THREAD

**Issue by robertwolter** [geckolinux/geckolinux-project#55]
I used GeckoLinux_ROLLING_XFCE.x86_64-999.180607.0.iso for installation and chose "German" (or really "Deutsch") and the variant "de_DE.utf8" as my language. After the installation and running the language installation script the DE still showed up in English. 

Some LC-variables contained "en_US.utf8" but they were not defined in /etc/locale.conf, so I added them manually. After a reboot the system language was still English and it turned out that there was still one RC_LANG="en_US.utf8" entry in /etc/sysconfig/language.

After changing it to RC_LANG="de_DE.UTF-8" the system language is now German. Well, "almost completely" German, some programs still show up in English though the corresponding language packages are installed, e.g. pluma, and parts of the menus still have English entries.

![screenshot_2018-06-15_17-37-37](https://user-images.githubusercontent.com/18753171/41484619-d2eed6ac-70dd-11e8-98c4-c08383ebf94c.png)
![screenshot_2018-06-15_17-42-10](https://user-images.githubusercontent.com/18753171/41484639-e2e2bfba-70dd-11e8-9e6b-f96cade2073c.png)
![bildschirmfoto_2018-06-15_20-49-31](https://user-images.githubusercontent.com/18753171/41484653-e93d8a7a-70dd-11e8-8f74-0a94d0328825.png)

**Comment by robertwolter** [comment]
Current state:
![bildschirmfoto_2018-06-15_20-59-52](https://user-images.githubusercontent.com/18753171/41485009-1e37dc2a-70df-11e8-9fc2-04ae69c83fcc.png)

**Comment by robertwolter** [comment]
Mixed entries:
![bildschirmfoto_2018-06-15_21-05-15](https://user-images.githubusercontent.com/18753171/41485192-e60aadcc-70df-11e8-84f3-532a39e8ff55.png)

**Comment by geckolinux** [comment]
Hi there, thanks for the detailed report.

Regarding the first problem of the system being in English after installation, I admit this is a known bug, because the installer allows changing the installer language, but it doesn't actually set the system language. I'll add this to my todo list and see what the Calamares installer folks say about resolving this. But the workaround is pretty easy after installation:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-install-non-english-languages


Regarding some menu items not being translated even after setting the correct language variables, that is not specific to GeckoLinux. Please file a bug report with openSUSE and/or with the application developer about items with missing translations.

Thanks again.

**Comment by robertwolter** [comment]
> Regarding some menu items not being translated even after setting the correct language variables, that is not specific to GeckoLinux.

But in original Tumbleweed this does not occur, neither for XFCE panel nor other programs.
![bildschirmfoto-17](https://user-images.githubusercontent.com/18753171/41499505-5b319c5e-7181-11e8-8ccb-893fdabbd88b.png)

**Comment by geckolinux** [comment]
Hi, could you please give me a screenshot of this part of your YaST Software?

![screenshot from 2018-06-16 09-53-41](https://user-images.githubusercontent.com/2692138/41499739-50fcf692-714b-11e8-8327-495d0c6f2284.png)

**Comment by geckolinux** [comment]
Hi, could you please give me a screenshot of your YaST Language settings?
![screenshot from 2018-06-16 09-57-21](https://user-images.githubusercontent.com/2692138/41499763-bcbec28e-714b-11e8-80c7-e3613dcd0d70.png)

**Comment by geckolinux** [comment]
OK, I found the missing packages. Please install:
`gtk2-lang`
`gtk3-lang`
I'll add these packages to the language installer in the next release.

Thanks for helping me identify this bug.

**Comment by robertwolter** [comment]
Yes, now it works :)

**Comment by geckolinux** [comment]
Cool, I'm reopening the bug report as a reminder for me to add those missing packages to the language installer script for future releases.

**Comment by robertwolter** [comment]
OK ;)

**Comment by candrapersada** [comment]
add `-lang` for all desktop and package other and add information how to install `-lang` for tumbleweed and leap

**Comment by pijano42** [comment]
Hi. i have the same problem with spanish.

**Comment by geckolinux** [comment]
Fixed in the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719

**Comment by jobukkit** [comment]
This is not fixed for me in GeckoLinux Static 15.3. Much of GNOME is in English, despite both GNOME settings and YaST correctly being set to Dutch by the installer.

**Comment by geckolinux** [comment]
Hi, please confirm that you ran the GeckoLinux Language Installer script.

**Comment by jobukkit** [comment]
Sorry, I assumed that the settings showing the language meant it was already installed 😳

**Comment by geckolinux** [comment]
Also sorry for the slightly more complicated process for language support installation in GeckoLinux. The way that GeckoLinux configures the Zypper package manager to avoid some common openSUSE annoyances makes it harder to install language packages.
